apiVersion: v1
kind: Secret
metadata:
  name: hr-rag-secret
  namespace: hr-rag
type: Opaque
stringData:
  POSTGRES_USER: "raguser"
  POSTGRES_PASSWORD: "ragpassword"
  GEMINI_API_KEY: "your_gemini_api_key_here"
  LLM_API_KEY: "your_gemini_api_key_here"
  COHERE_API_KEY: ""
  LANGSMITH_API_KEY: ""
